apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: dicoding-db
spec:
  serviceName: mongo
  replicas: 3
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:4.4 # image mongodb tag 4.4
        env: # menambahkan environment variabel ke dalam container
          - name: MONGO_INITDB_ROOT_USERNAME_FILE
            value: /etc/mongo-credentials/MONGO_ROOT_USERNAME
          - name: MONGO_INITDB_ROOT_PASSWORD_FILE
            value: /etc/mongo-credentials/MONGO_ROOT_PASSWORD
        command: # Menentukan perintah yang akan dijalankan saat container dijalankan
          - mongod
          - "--replSet"
          - rs0
          - "--bind_ip_all"
        ports:
        - containerPort: 27017 # Menentukan port pada container
          name: mongo
        volumeMounts: # menentukan bagaimana volume yang ditentukan dalam volumes akan dipasang atau di-mount ke dalam container di dalam pod
        - name: mongo-persistent-storage
          mountPath: /data/db
        - name: mongo-secrets
          mountPath: /etc/mongo-credentials 
      volumes:
        - name: mongo-persistent-storage #  Menentukan volume yang digunakan oleh pod atau aplikasi
          persistentVolumeClaim:
            claimName: mongo-pv-claim
        - name: mongo-config-map
          configMap:
            name: mongo-config
            items: 
              - key: mongo.conf
                path: mongo.conf
        - name: mongo-secrets
          secret:
            secretName: mongo-secret
