version: "2.1"
orbs:
  docker: circleci/docker@2.2.0

jobs:
  build:
    executor: docker/machine
    steps:
      - checkout
      - run:
          name: Test Dockerfile
          command: ./hadolint Dockerfile
      - run:
          name: Docker Build and push
          command: |
            chmod +x build_push_image_karsajobs_ui.sh 
            bash ./build_push_image_karsajobs_ui.sh 

workflows:
  lint-and-build-push:
    jobs:
      - build

dependencies:
  pre:
    - curl -L https://github.com/hadolint/hadolint/releases/download/v1.18.1/hadolint-Linux-x86_64 -o hadolint
    - chmod +x hadolint
