version: "2.1"
orbs:
  docker: circleci/docker@2.1.4
jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - docker/dockerlint:
          dockerfile: Dockerfile
          treat-warnings-as-errors: true
      - run:
          name: menjalankan unit test untuk backend
          command: go test -v -short --count=1 $(go list ./...)
      - run:
          name: Docker Build and push
          command: |
            #!/bin/bash -eo pipefail
            chmod +x build_push_image_karsajobs.sh
            bash ./build_push_image_karsajobs.sh
workflows:
  lint-and-build:
    jobs:
      - build
