version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - run:
          name: Install hadolint
          command: |
            curl -L -o hadolint https://github.com/hadolint/hadolint/releases/download/v1.17.5/hadolint-Linux-x86_64
            chmod +x hadolint
            sudo mv hadolint /usr/local/bin
      - run:
          name: Lint Dockerfile
          command: hadolint Dockerfile
      - run:
          name: Docker Build and push
          command: |
            #!/bin/bash -eo pipefail
            chmod +x build_push_image_karsajobs.sh
            ./build_push_image_karsajobs.sh

workflows:
  version: 2
  lint-and-build:
    jobs:
      - build

jobs:
  test-app:
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - run: go test -v -short --count=1 $(go list ./...)

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - test-app:
          requires:
            - build
