apiVersion: v1
kind: Service
metadata:
  name: karsajobs 
  labels:
    app: karsajobs
    namespace: dicoding-be # Namespace khusus backend
spec:
  type: NodePort # Service akan tersedia di semua node di dalam cluster pada port yang ditentukan (node port)
  selector:
    app: karsajobs
  ports: # konfigurasi Service Kubernetes ini menentukan bagaimana Service akan berkomunikasi dengan request yang datang dari luar cluster
    - port: 8080 # port yang akan digunakan oleh Service untuk mendengarkan request dari luar cluster
      protocol: TCP # protokol yang akan digunakan oleh Service untuk berkomunikasi dengan request yang datang
      targetPort: 8080 # port yang akan digunakan oleh Service untuk mengirim request ke pod yang terhubung
      nodePort: 30001 # mendengarkan request pada port 30001 pada node yang menjalankan pod yang terhubung dengan Service
